import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

public class WMS_EXP5_B {
	public static String encryptThisString(String input) {
		try {
			MessageDigest md = MessageDigest.getInstance("SHA-1");

			byte[] messageDigest = md.digest(input.getBytes());
			BigInteger no = new BigInteger(1, messageDigest);
			String hashtext = no.toString(16);
			while (hashtext.length() < 32) {
				hashtext = "0" + hashtext;
			}
			return hashtext;
		} catch (NoSuchAlgorithmException e) {
			throw new RuntimeException(e);
		}
	}

	public static void main(String args[]) throws NoSuchAlgorithmException {
		Scanner in = new Scanner(System.in);
		System.out.println("Enter your String: ");
		String s = in.nextLine();
		System.out.println("HashCode Generated by SHA-1 for: ");
		System.out.println(s + " is : " + encryptThisString(s));
		in.close();
	}
}
